# fly.toml app configuration file generated for wordtracker-api on 2024-11-27T15:20:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mylib'
primary_region = 'lhr'

[build]
  dockerfile = './app/api/Dockerfile'

[[services]]
  min_machines_running = 1
  internal_port = 80
  auto_stop_machines = 'stop'
  auto_start_machines = true
  processes = ['app']
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
