name: Deploy to Fly.io

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/app
      DOTENV_PRIVATE_KEY_VAULT: ${{ secrets.DOTENV_PRIVATE_KEY_VAULT }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy with flyctl
        run: |
          flyctl deploy --no-cache --remote-only --build-secret DOTENV_PRIVATE_KEY_VAULT=${{ secrets.DOTENV_PRIVATE_KEY_VAULT }}
