# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    if: github.repository != 'webventurer/python-template'
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/mylib
      DOTENV_PRIVATE_KEY_VAULT: ${{ secrets.DOTENV_PRIVATE_KEY_VAULT }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          [ -f requirements.txt ] && pip-sync requirements.txt requirements-dev.txt || pip-sync requirements-dev.txt
      - name: Check dotenvx private key is present
        run: |
          if [ -z "${DOTENV_PRIVATE_KEY_VAULT}" ]; then
            echo "DOTENV_PRIVATE_KEY_VAULT is not set"
            exit 1
          fi
      - name: Install dotenvx
        run: |
          curl -sfS https://dotenvx.sh/install.sh | sh
          dotenvx run --env-file .env.vault -- python check_env.py
      - name: Run linter
        run: make lint
      - name: Check formatting
        run: make format
      - name: Check types
        run: make types
      - name: Run tests
        run: |
          dotenvx run --env-file .env.vault -- pytest -o console_output_style=classic -v || ([ $? = 5 ] && exit 0 || exit $?)
