jobs:
  build:
    env:
      PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/mylib
      PRIVATE_REPO_ACCESS_TOKEN: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
      GIT_TERMINAL_PROMPT: 1
    steps:
      - name: Configure git for authentication
        run: |
          git config --global url."https://${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
